[window]
padding.x = 12
padding.y = 12
decorations = "none"

[font]
size = 12.0

[colors.primary]
background = '#000000'
foreground = '#ffffff'

[colors.cursor]
cursor = '#ffffff'
text = '#000000'

[colors.selection]
background = '#33467c'
text = '#ffffff'

[colors.normal]
black = '#000000'
red = '#f7768e'
green = '#9ece6a'
yellow = '#e0af68'
blue = '#7aa2f7'
magenta = '#bb9af7'
cyan = '#7dcfff'
white = '#ffffff'

[colors.bright]
black = '#33467c'
red = '#ff9e64'
green = '#b9f27c'
yellow = '#e0af68'
blue = '#7da6ff'
magenta = '#bb9af7'
cyan = '#7dcfff'
white = '#ffffff'