[meta]
version = 1
name = "TokyoLED Night"
description = "High-contrast OLED Tokyo Night theme."
variant = "dark"
inherits = "vicinae-dark"

[colors.core]
background = "#000000"
foreground = "#ffffff"
secondary_background = "#000000"
border = "#33467c"
accent = "#7aa2f7"

[colors.list.item.hover]
background = "#33467c"
foreground = "#ffffff"

[colors.list.item.selection]
background = "#33467c"
foreground = "#ffffff"

[colors.accents]
blue = "#7aa2f7"
green = "#9ece6a"
magenta = "#bb9af7"
orange = "#ff9e64"
purple = "#bb9af7"
red = "#f7768e"
yellow = "#e0af68"
cyan = "#7dcfff"
